### ISSUE TITLE
Stackdump script failed when using Post.xml produced by this script

### ISSUE THREAD

**Issue by ryanschulz46** [RubenNL/stackdump-lowram#2]
[post] PARSING POSTS...
[post] start parsing posts.xml...
Traceback (most recent call last):
  File "./python/src/stackdump/commands/import_site.py", line 927, in <module>
    cmd_options.base_url, answer_yes=cmd_options.answer_yes)
  File "./python/src/stackdump/commands/import_site.py", line 885, in import_site
    xml.sax.parse(xml_path, handler)
  File "/Users/ryanschulz/.pyenv/versions/2.7.13/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/Users/ryanschulz/.pyenv/versions/2.7.13/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/Users/ryanschulz/.pyenv/versions/2.7.13/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/Users/ryanschulz/.pyenv/versions/2.7.13/lib/python2.7/xml/sax/expatreader.py", line 217, in feed
    self._err_handler.fatalError(exc)
  File "/Users/ryanschulz/.pyenv/versions/2.7.13/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: /Users/ryanschulz/Documents/stackoverflow/Posts.xml:4:2: junk after document element

**Comment by ryanschulz46** [comment]
I'll try this fix next week when I am back from travel!

I am curious though, does this script help solve the problem with PostHistory.xml (100+gb) and Answers.xml being so large? Or do you not include those in your folder when you run the script?

**Comment by RubenNL** [comment]
My script only changes the Posts.xml file. Stackdump uses Posts.xml, Users.xml and Comments.xml. the others are ignored.

Also, make sure you use my last version of stackdump. I reverted an old commit, which made everything much slower.

**Comment by JGKle** [comment]
This issue persists.  I pulled the latest version of stackdump-lowram, and am also using the latest stackdump from https://github.com/RubenNL/stackdump.  Screenshot (showing the same exception as above): https://lnk2.tk/snaps/2020-04-07_17.57.11.png.

It seems like this script is producing malformed xml - if you open posts.xml & compare it to the original, you'll see that it's missing the document node.

**Comment by RubenNL** [comment]
Could you send a screenshot/copy of the first couple lines of the Posts.xml produced from the script?

For me the stackdump-lowram and stackdump both work, so this surprises me.

**Comment by JGKle** [comment]
Posts.xml produced by the script: https://lnk2.tk/snaps/2020-04-07_23.20.53.png

Original posts.xml: https://lnk2.tk/snaps/2020-04-07_23.20.03.png

**Comment by JGKle** [comment]
Do those give any insight as to why it might be failing?

**Comment by teoman002** [comment]
You were talking about malformed xml?

Have a look at the script:
https://github.com/RubenNL/stackdump-lowram/blob/249621697660508340be281a7d0b07a2a808162d/start.sh#L13

At first we copy the header of the xml to Posts.xml
`head -n2 Posts.xml-old > Posts.xml`
A little bit later the file that contains the header will be deleted
`rm Posts.xml`
Since no other command recovers the header, it is lost. I recommend to remove the aforementioned line to make the script work.

**Comment by RubenNL** [comment]
i have forgotten this issue, and have since updated the code a lot, which is visible in the master. the original code with the fix is in the 1.0 branch.

**Comment by JGKle** [comment]
Excellent! Just to clarify: are you recommending using the master or 1.0 branch as the current/stable solution?

**Comment by RubenNL** [comment]
The master

**Comment by JGKle** [comment]
Sadly, it didn't seem to work :(  Running posts.xml through the current master, then trying to build using the StackDump from https://github.com/RubenNL/stackdump, still yielded a MemoryError.  Made it through comments.xml & users.xml, then died during posts.xml.  

Should I post this as a separate issue?

Screenshot: https://lnk2.tk/snaps/2020-06-05_22.13.08.png

```Traceback (most recent call last):
  File "./python/src/stackdump/commands/import_site.py", line 927, in <module>
    cmd_options.base_url, answer_yes=cmd_options.answer_yes)
  File "./python/src/stackdump/commands/import_site.py", line 885, in import_site
    xml.sax.parse(xml_path, handler)
  File "/usr/local/lib/python2.7/xml/sax/__init__.py", line 33, in parse
    parser.parse(source)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 220, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 339, in end_element
    self._cont_handler.endElement(name)
  File "./python/src/stackdump/commands/import_site.py", line 364, in endElement
    self.commit_finished_questions()
  File "./python/src/stackdump/commands/import_site.py", line 390, in commit_finished_questions
    self.commit_questions(questions_to_commit, commit=False)
  File "./python/src/stackdump/commands/import_site.py", line 548, in commit_questions
    self.solr.add(questions, commit=commit)
  File "/app/stackdump/python/packages/pysolr.py", line 794, in add
    return self._update(m, commit=commit, waitFlush=waitFlush, waitSearcher=waitSearcher)
  File "/app/stackdump/python/packages/pysolr.py", line 399, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "/app/stackdump/python/packages/pysolr.py", line 291, in _send_request
    log_body = repr(body)
MemoryError

**Comment by JGKle** [comment]
Alright, went ahead & made a proper new issue here #4
